services:
  - type: web
    name: serviceease-frontend
    env: static
    staticPublishPath: build
    buildCommand: npm run build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
